### ISSUE TITLE
Returns just one variation photo even if you request for more

### ISSUE THREAD

**Issue by mtkgeek** [anasfik/openai#100]
The `OpenAI.instance.image.variation` method always returns just a single item even when n > 1. This is not case with the `create` and `edit` methods.

**Comment by anasfik** [comment]
This have been fixed, I will push version 4.1.1, please upgrade and confirm that it has been fixed:
 - [https://pub.dev/packages/dart_openai](https://pub.dev/packages/dart_openai)
