### ISSUE TITLE
Can we whisper be used locally?

### ISSUE THREAD

**Issue by guyluz11** [anasfik/openai#101]
Whisper is open source and I know that it got implemented in several languages to run locally.
Can it also run locally on dart native using this package?

**Comment by FelixMittermeier** [comment]
You're right, did not know this actually. Quite cool, then we could run it without costs.

Looks like some guy is already working on this: https://github.com/lyledean1/flutter_whisper.cpp but so far only iOS support, so looks like it's still in development

**Comment by guyluz11** [comment]
I've added an issue to support dart native but I have a feeling that this package is for flutter use and will continue to be as it is using fluttee only packages

**Comment by guyluz11** [comment]
We can also have the option of using c++ version using Dart ffi.
It could be much easier than writing the code in Dart

**Comment by anasfik** [comment]
Hello @guyluz11.

This seems cool to exist for Dart/Flutter. However, it is not going to be supported in this package.

if there are real interest and need for it, I can create another Dart package for this, we can bind to existent platform-specific packages/libraries via Dart bindings and `dart:ffi`..

**Comment by anasfik** [comment]
Hi,

What do you think about having a Dart API by calling whisper commands via the `https://pub.dev/packages/process_run` package.

Would you be able to collaborate with me on it?

**Comment by guyluz11** [comment]
From my experience using process_run is incorrect and will lead to a lot of trouble.

**Comment by anasfik** [comment]
Makes sense after rethinking it, thank you.

I will close this for now.
