### ISSUE TITLE
 Add proxy setting interface

### ISSUE THREAD

**Issue by DogeVenci** [anasfik/openai#102]
Add proxy setting interface like http or socks5 proxy to connect endpoint

**Comment by anasfik** [comment]
Hello @DogeVenci.

short answer: this is not going to be implemented.

long answer: the package is made to reflect OpenAI APIs only. However, we expose API for changing the `baseUrl` that will be used, feel free to manage your own proxy server to point to OpenAI base url API based on your needs, and then you can set and use it with:

```dart
OpenAI.baseUrl = "YOUR_PROXIED_BASE_URL";
```
