### ISSUE TITLE
Add support for choosing model(dal-e-3) for image generation

### ISSUE THREAD

**Issue by dmisiuk** [anasfik/openai#108]
After new release it's possible to set model to dal-e-3 or default dal-e-2 [reference](https://platform.openai.com/docs/api-reference/images/create)

**Comment by anasfik** [comment]
Hello @dmisiuk.

I don't really get it, why can't you change the `model` field value to the model (`dal-e-3`) and get what you need? Am I missing something?

**Comment by FelixMittermeier** [comment]
I looked it up and also cannot find a `model` field when using `OpenAI.instance.image.create`. Can just change the model for text completion etc. No hurries, take your time, the library is great :-)

Just wanted to let you know that it's indeed missing to my knowledge.

**Comment by anasfik** [comment]
Hello @FelixMittermeier.

Check #115 pr, it covers having this issue fixed and now the model field is exposed to be set to what you need, the latest 4.1.0 deployment should work fine with it.

**Comment by FelixMittermeier** [comment]
Cool, thanks a lot. Much appreciated :-)

**Comment by dmisiuk** [comment]
Thank you for implementing this so quickly!
