### ISSUE TITLE
Support JSON mode

### ISSUE THREAD

**Issue by RockStone** [anasfik/openai#110]
Can we add https://platform.openai.com/docs/guides/text-generation/json-mode as for `response_format`?

**Comment by anasfik** [comment]
This is scheduled for being implented..

**Comment by anasfik** [comment]
Hello,
the JSON mode feature is implemented in the package and is being tested.

After the next release, you will be able to customize the `response_format` and achieve the behavior you need.

I will close this issue as resolved.
