### ISSUE TITLE
Support Seed Feature for consistent output

### ISSUE THREAD

**Issue by MalikSamiAwan** [anasfik/openai#111]
https://cookbook.openai.com/examples/deterministic_outputs_with_the_seed_parameter

**Comment by anasfik** [comment]
Hello @MalikSamiAwan.

I will work on new things once I get older issues fixed, if you can code implement this or anyone can from the community, I will be happy to review and merge it.

**Comment by anasfik** [comment]
Hello,

the seed functionality has been implemented and tested with the `gpt-3.5-turbo-1106` model, in addition to the `system_fingerprint` field in the response.

It will be available for use in the next release.

This has been said, I will close this issue as resolved.
