### ISSUE TITLE
pubspec resolve failed

### ISSUE THREAD

**Issue by t-m-z** [anasfik/openai#119]
after adding dart_openai: ^4.1.2 to my pubspec.yaml and trying "pub upgrade" I receive an error while resolving dependencies:

"Note: meta is pinned to version 1.9.1 by flutter from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because every version of flutter from sdk depends on meta 1.9.1 and dart_openai >=4.1.0 depends on meta ^1.11.0, flutter from sdk is incompatible with dart_openai >=4.1.0.
So, because your app depends on both dart_openai ^4.1.2 and flutter from sdk, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on dart_openai: flutter pub add dart_openai:^4.0.0"

**Comment by leifhacks** [comment]
Note: After adding `meta: ^1.9.1` to the `dependency_overrides` section I get a similar message for `collection`:
```
Because every version of flutter_test from sdk depends on collection 1.17.2 and dart_openai 4.1.2 depends on collection ^1.18.0, flutter_test from sdk is incompatible with dart_openai 4.1.2.
And because no versions of dart_openai match >4.1.2 <5.0.0, flutter_test from sdk is incompatible with dart_openai ^4.1.2.
```

**Comment by PeperMarkreel** [comment]
> Thank you for giving me this notification, it was changed in a pull requests and I didn't notice it.

Any time line on when the fix will be published?

**Comment by anasfik** [comment]
Thank you @PeperMarkreel .

I will release 4.1.3 to Pub.

**Comment by anasfik** [comment]
Can you update to 4.1.3 and confirm if the behavior still occurs ?

**Comment by t-m-z** [comment]
I did an update to 4.1.3 and could build an apk without any errors.
Thanks for this quick fix
