### ISSUE TITLE
dall-e 3

### ISSUE THREAD

**Issue by peoplesdriver** [anasfik/openai#120]
hi, it's the package updated for dall-e 3?
how can i use the vision model?

kind regards,

Laur

**Comment by anasfik** [comment]
There is an option for setting the `model` in the image methods, can you clarify your issue more?

**Comment by peoplesdriver** [comment]
hi,

OpenAIImageModel image = await OpenAI.instance.image.create(
          prompt: imagePrompt,
          model: 'dall-e-3',
          n: 1,
          size: OpenAIImageSize.size512,
          responseFormat: OpenAIImageResponseFormat.b64Json,
        );

The named parameter 'model' isn't defined.

**Comment by peoplesdriver** [comment]
Problem solved, I didn't updated the package first.
