### ISSUE TITLE
Full JSON response for debugging?

### ISSUE THREAD

**Issue by catallo** [anasfik/openai#121]
I couldn't find any information in the documentation regarding debug options, specifically the ability to print out the full JSON response when making API calls. Is there a way to enable such debugging?

**Comment by anasfik** [comment]
This seems good to have.

**Comment by anasfik** [comment]
Now, at version 4.1.4, you can log responses from async methods with [this](https://github.com/anasfik/openai#enable-debugging-and-logs).

update the package and try it.

**Comment by catallo** [comment]
That was fast! :+1:
