### ISSUE TITLE
Gpt-4-vision 

### ISSUE THREAD

**Issue by peoplesdriver** [anasfik/openai#122]
Hi,

Do you have any documentation or examples on how to use the new features of gpt-4-vision? 

Thanks

**Comment by anasfik** [comment]
I guess you will need to check the new docs for chat completions.

Also check the examples folder, I do an example code for almost everything there.

**Comment by anasfik** [comment]
Here, check this doc at [Create Chat Completion](https://github.com/anasfik/openai#create-chat-completion) section.

And this [example](https://github.com/anasfik/openai/blob/main/example/lib/chat_completion_example.dart)

**Comment by anasfik** [comment]
Closing this..
