### ISSUE TITLE
How to respond to toolCalls?

### ISSUE THREAD

**Issue by odedsolutions** [anasfik/openai#127]
I figured this much myself:
```dart
final functionMessage = OpenAIChatCompletionChoiceMessageModel(
  content: [
    OpenAIChatCompletionChoiceMessageContentItemModel. text(functionResponse),
  ],
  role: OpenAIChatMessageRole.tool,
).asRequestFunctionMessage(toolCallId: toolCall.id!);

messageToSend.add(functionMessage);
```

But I keep getting a serialization error:
`Converting object to an encodable object failed: Instance of 'OpenAIChatCompletionChoiceMessageContentItemModel'`

Am I doing it right? Any help will be greatly appreciated 🙏🏻
Thanks!

**Comment by odedsolutions** [comment]
Found the cause - content was naivly encoded. This code works for me:
```
 @override
  Map<String, dynamic> toMap() {
    return {
      ...super.toMap(),
      "tool_call_id": toolCallId,
    };
    // return {
    //   "role": role.name,
    //   "content": content?.map((contentItem) => contentItem.toMap()).toList(),
    //   "tool_call_id": toolCallId,
    // };
  }
```

**Comment by mickeyjoes** [comment]
@odedsolutions I got the exact same issue. Where did you add that code for the toMap override?

**Comment by odedsolutions** [comment]
Inside my local pub cache for the moment. It's in file called message.dart, but just click on the definition of RequestFunctionMessage and it will take you there.

**Comment by mickeyjoes** [comment]
Gotcha, I can confirm changing to below like in your code it now works. 

```dart
  @override
  Map<String, dynamic> toMap() {
    return {
      "role": role.name,
      "content": content?.map((toolCall) => toolCall.toMap()).toList(),
      "tool_call_id": toolCallId,
    };
  }
  ```
  
  I look forward to fix in the next release.
  Thanks!

**Comment by sherazahmad720** [comment]
but now where i can add this to fix this issue?

**Comment by mickeyjoes** [comment]
For me on Ubuntu its in pub cache here:
 ~/.pub-cache/hosted/pub.dev/dart_openai-4.1.4/lib/src/core/models/chat/sub_models/choices/sub_models/message.dart at the end of file line 140 replace toMap with the fixed toMap code.
But hopefully there will be a fix soon in the next version and this "hack" should not be needed.

**Comment by odedsolutions** [comment]
This "Hack" would probably just be pulled into the code :)

I'll try to get to it today

**Comment by odedsolutions** [comment]
@anasfik let me know if you want me to do it. (not sure how honestly 😅)

**Comment by anasfik** [comment]
> ```dart
> toolCall
> ```

Yes, very precise on this, thank you!
I will release

**Comment by mickeyjoes** [comment]
Great, thanks @anasfik! Appreciate your work. I'll try the new release during this week and confirm.

**Comment by anasfik** [comment]
I released version 5.0.0 with the fix and some other changes:
- [https://pub.dev/packages/dart_openai](https://pub.dev/packages/dart_openai)

Until you can confirm that the issue is fixed 100%, this issue will stay open.

**Comment by mickeyjoes** [comment]
Awesome! I upgraded to the latest version 5.0.0 and I can confirm the fix works, thanks!

**Comment by odedsolutions** [comment]
Working for me too on 5.0.0. Thanks!
