### ISSUE TITLE
Breaking changes should be listed in the CHANGELOG 🙏 

### ISSUE THREAD

**Issue by chirag729** [anasfik/openai#128]
The release notes for 4.1.3 do not list the breaking changes made to OpenAIChatCompletionChoiceMessageContentItemModel. Any update that is going to break peoples code should technically be done as a major version update

**Comment by anasfik** [comment]
Yes, you right! my bad I will make this happen.

**Comment by anasfik** [comment]
Thank you again, I released 5.0.0 now with the breaking changelogs.

Closing this.

**Comment by anasfik** [comment]
- [https://pub.dev/packages/dart_openai](https://pub.dev/packages/dart_openai)

**Comment by chirag729** [comment]
@anasfik Thanks for updating. Ideally breaking changes should be listed first in the changelog highlighted in **bold**. Take a look at https://pub.dev/packages/riverpod/changelog for a good example
