### ISSUE TITLE
Is there any complete example with the stream?

### ISSUE THREAD

**Issue by desmeit** [anasfik/openai#130]
I can't find a really usable example with the stream. How exactly do you use the stream in a chat? I've only found this, but here a new stream is created for each request:

https://github.com/iqfareez/flutter_chatgpt/blob/main/lib/screens/chat_page.dart

This is not good if the user enters something while the assistant is answering.
How could such a scenario be handled?

**Comment by anasfik** [comment]
Check the [example](https://github.com/anasfik/openai/tree/main/example) folder of the project, it have updated examples that you can use.

**Comment by anasfik** [comment]
I am closing this!

**Comment by desmeit** [comment]
@anasfik 
Thanks but which example did you update?
[chat_example_with_tools.dart](https://github.com/anasfik/openai/blob/main/example/lib/chat_example_with_tools.dart)
is updated but not the stream example.

it would be nice to see how the stream is updated when new messages are added.

**Comment by thaidmfinnick** [comment]
Hi @anasfik, I have same question as @desmeit. Do we need create new stream each time we create new message? I can not see any example in repo describing this situation. Hope you can reply!
