### ISSUE TITLE
[question] Is it safe to use this package on release?

### ISSUE THREAD

**Issue by Epiwish** [anasfik/openai#136]
I'm using envied package to store my OpenAI API key. But still, is it really safe to use this package on release? Should I go for a server-side solution instead of using this package?

**Comment by Epiwish** [comment]
> I dont think so.
> 
> this is openai latest python code client model:
> 
> ```
> # File generated from our OpenAPI spec by Stainless.
> 
> from __future__ import annotations
> 
> from typing import Optional
> from typing_extensions import Literal, Required, TypedDict
> 
> __all__ = ["ChatCompletionSystemMessageParam"]
> 
> 
> class ChatCompletionSystemMessageParam(TypedDict, total=False):
>     content: Required[Optional[str]]
>     """The contents of the system message."""
> 
>     role: Required[Literal["system"]]
>     """The role of the messages author, in this case `system`."""
> ```
> 
> this is how lib defines:
> 
> ```
> messages: (OpenAIChatCompletionChoiceMessageModel(role: OpenAIChatMessageRole.user, content: [OpenAIChatCompletionChoiceMessageContentItemModel(type: text, text: 发热管, imageUrl: null)], ), OpenAIChatCompletionChoiceMessageModel(role: OpenAIChatMessageRole.system, content: [
> ```
> 
> It doesn't really stick to original format, all my openai server are down by upgrade latest client dart code....

My question was more about security concerns. Under normal circumstances, using API Key through the client is not a very healthy situation. I'm just wondering if packages like envied provide any protection against theft of my API Key. Because otherwise, the API Key may fall into the hands of attackers through reverse engineering.

**Comment by lucasjinreal** [comment]
Oh, I found the reson is that openai just support 2 kinds of ChatMessages, now I fixed it!
