### ISSUE TITLE
[Transcription] Bad state: Stream has already been listened to

### ISSUE THREAD

**Issue by pilgrim1385** [anasfik/openai#139]
When using the Transcription feature, I encountered an error

```plaintext
[OpenAI] accessing endpoint: /audio
[OpenAI] starting request to https://api.openai.com/v1/audio/transcriptions
[OpenAI] request to https://api.openai.com/v1/audio/transcriptions finished with status code 200
flutter: Bad state: Stream has already been listened to.
flutter: #0      _StreamController._subscribe (dart:async/stream_controller.dart:686:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:836:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
#3      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
#4      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
#5      _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
#6      _HttpIncoming.listen (dart:_http/http_impl.dart:442:49)
#7      _HttpClientResponse.listen (dart:_http/http_impl.dart:713:19)
#8      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
#9      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
#10     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
#11     StreamView.listen (dart:async/stream.dart:2214:20)
#12     new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:49:16)
#13     _BoundSinkStream.<…>
[OpenAI] starting decoding response body
[OpenAI] {
  "text": "hello"
}
```

Here is my code

```flutter
  Future<void> runTranscription(String filePath) async {
    try {
      OpenAIAudioModel transcription = await OpenAI.instance.audio.createTranscription(
        file: File(filePath),
        model: "whisper-1",
        responseFormat: OpenAIAudioResponseFormat.json,
      );
      if (transcription.text.isNotEmpty == true) {
        sendTextMessage(text: transcription.text);
      }
    } catch (error, stackTrace) {
      print(error.toString());
      print(stackTrace);
    }
  }
```

**Comment by anasfik** [comment]
I see that the streaming error doesn't relate to the `createTranscription`, since all the `audio` methods are not `Stream`, the streaming functionality exists only in the `chat`, `completions` and `fine-tune` methods.

seeing the error while the audio request is happening makes me suspect that you are trying to combine a streaming method with the `createTranscription` method in the same workaround.

would be happy to help, if you can provide me with more context

**Comment by pilgrim1385** [comment]
Yes, I first record audio using flutter_sound, then I convert the recording to text through createTranscription, and finally, I use the text for chat.

This is part of my code:

```Dart
  Future<void> startRecorder() async {
    // flutter sound only support iOS/Android/Web
    if (Platform.isIOS || Platform.isAndroid || kIsWeb) {
      var id = nanoid();
      await _recorder.startRecorder(codec: Codec.aacMP4, toFile: "$id.mp4");
    }
  }

  Future<void> stopRecorder() async {
    // flutter_sound only support iOS/Android/Web
    if (Platform.isIOS || Platform.isAndroid || kIsWeb) {
      String? filePath = await _recorder.stopRecorder();
      if (filePath?.isNotEmpty == true) {
        runTranscription(filePath!);
      }
    }
  }

  Future<void> runTranscription(String filePath) async {
    try {
      OpenAIAudioModel transcription = await OpenAI.instance.audio.createTranscription(
        file: File(filePath),
        model: "whisper-1",
        responseFormat: OpenAIAudioResponseFormat.json,
      );
      // The code cannot run up to this point, it goes to catch block.
      print("Received Transcription Result");
      if (transcription.text.isNotEmpty == true) {
        sendChatMessage(text: transcription.text);
      }
    } catch (error, stackTrace) {
      EasyLoading.showToast(error.toString());
      print(error.toString());
      print(stackTrace);
    }
  }

  Future<void> sendChatMessage({String? text}) async {
    chatStream = OpenAI.instance.chat.createStream(
      model: model,
      messages: chatGPTModels!,
      n: 1,
      maxTokens: 4096,
    );

    chatStream!.listen((streamChatModel) {
    }, onDone: () {
      if (isTTSOpen == true) {
        runSpeech(gptContentModel.text ?? "");
      }
    }, onError: (error) {
      EasyLoading.showToast(error.toString());
      print(error.toString());
    }, cancelOnError: true);
  }
```

**Comment by pilgrim1385** [comment]
When I set OpenAI.showResponsesLogs = true, it throws an error; when set to false, the error disappears.

I think this bug is caused by the following reason:

In OpenAINetworkingClient.fileUpload function, we called request.send()
`final http.StreamedResponse response = await request.send().timeout(OpenAIConfig.requestsTimeOut);`
and we got a StreamedResponse.
![screenshot-20231215-175525](https://github.com/anasfik/openai/assets/8338907/c392ab2d-9d2d-4a08-b455-212f7401fbca)

This response has a stream, and it's a single-subscription stream.
![screenshot-20231215-180446](https://github.com/anasfik/openai/assets/8338907/5cd95adf-e43d-48d1-af46-fa010decd16c)

In OpenAILogger.logResponseBody function, we called response.stream.bytesToString()
`final asString = await response.stream.bytesToString();`
![screenshot-20231215-180812](https://github.com/anasfik/openai/assets/8338907/ed2d2130-9f04-4b2a-8133-5b925d902bd1)

In bytesToString function, called`encoding.decodeStream(this);`
![screenshot-20231215-180924](https://github.com/anasfik/openai/assets/8338907/f3f4d0c4-126e-4f90-ad66-5e436a6135d9)

Here is decodeStream function
![screenshot-20231215-180939](https://github.com/anasfik/openai/assets/8338907/9cb3bee8-f6fd-49d3-99b8-6ffae714a73c)

In fold function, stream.listen function is called
![screenshot-20231215-210500](https://github.com/anasfik/openai/assets/8338907/be1188fd-3cd0-4322-a38b-3720cef2ba03)

Back to first screenshot, below OpenAILogger.logResponseBody, we called `final String responseBody = await response.stream.bytesToString();`, it will call stream.listen again.

But this stream is a single-subscription stream, so an error throw.

Hope this help.

**Comment by gaganyadav80** [comment]
In the file upload [method](https://github.com/anasfik/openai/blob/1f8e675fc12c533e1509bd75ee02264297a11ac2/lib/src/core/networking/client.dart#L565) also at LN 578 the `OpenAILogger.logResponseBody` subscribes to the response stream and then again at LN 584 it subscribes to the same single-subscription stream which then throw the error.

**Comment by li-xiaojun** [comment]
same issue

**Comment by anasfik** [comment]
Wow, the very nice catch here @pilgrim1385, thank you.

I will fix this.

**Comment by anasfik** [comment]
I made the `logResponseBody` to be called for either raw `String` responses, or the http `Reponse`, I will make sure to put this in mind when using this method.
