### ISSUE TITLE
Response from OpenAIStreamChatCompletionModel missing "usage"

### ISSUE THREAD

**Issue by Tryad0** [anasfik/openai#14]
In the response from OpenAI.instance.chat.createStream() I see everything from official API Reference but not "usage".

Official API from OpenAI Reference:

`{
  "id": "chatcmpl-123",
  "object": "chat.completion",
  "created": 1677652288,
  "choices": [{
    "index": 0,
    "message": {
      "role": "assistant",
      "content": "\n\nHello there, how may I assist you today?",
    },
    "finish_reason": "stop"
  }],
  "usage": {
    "prompt_tokens": 9,
    "completion_tokens": 12,
    "total_tokens": 21
  }
}
`

Thanks a lot for your work!

**Comment by anasfik** [comment]
Thank you for your note, I guess I might forget to expose it, I will review and fix it.

have a good day!

**Comment by rafaellop** [comment]
@anasfik How can I find the usage when using `OpenAIStreamChatCompletionModel`? I've got 1.9.1 from pub.dev
