### ISSUE TITLE
How to modify the baseURL of OpenAI?

### ISSUE THREAD

**Issue by DogeVenci** [anasfik/openai#15]
Suggest adding an interface to modify the OpenAIConfig.baseUrl
Because some regions' inability to directly access the official API endpoint of OpenAI

**Comment by anasfik** [comment]
Hello, sorry for late response, yes sure it can be exposed to the outside to be modified, but by what it can be replaced ? since all responsces of the library are based on OpenAI APIs.

if any kinf of error happens, the dev will get that error thrown, and so he will be aware.

**Comment by DogeVenci** [comment]
Due to certain countries or regions being unable to directly access the OpenAI API , Some people use Self-built reverse proxies like nginx to forward traffic to OpenAI API endpoint
Adding custom API endpoint or proxy options can make it more convenient for users to use.

**Comment by anasfik** [comment]
Does make since, thank for notifying me about it. I will expose its interface then.

**Comment by badboy-tian** [comment]
+1

**Comment by badboy-tian** [comment]
I add OpenAI.baseUrl https://github.com/anasfik/openai/pull/22

**Comment by badboy-tian** [comment]
@anasfik

**Comment by badboy-tian** [comment]
@anasfik Because openai has been banned in some country, we have to create a proxy server to forward the openai interface, so we hope we can set the baseUrl manually.

**Comment by anasfik** [comment]
@badboy-tian thank you, for your help. the contribution is merged, passes the test, and is available now in the 1.8.3 version.

**Comment by anasfik** [comment]
I will close this currently!
