### ISSUE TITLE
Unhandled Exception caused by jsonDecode(data) in postStream()

### ISSUE THREAD

**Issue by masa8** [anasfik/openai#154]
On 12 October 2023, 
when calling postStream() with version 4.0.0, 
the following error occurred about once every two times.

> ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unterminated string (at character 27)
> "{"rate_limit_usage": {

Note: Version 5.0.0 could be reproduced by debugger.

**Comment by masa8** [comment]
Fixed by this PR #153

**Comment by anasfik** [comment]
Thank you, it was merged.
