### ISSUE TITLE
Need to add the field 'usage' to OpenAIStreamChatCompletionModel

### ISSUE THREAD

**Issue by hnvmeta** [anasfik/openai#155]
I need to read the `total_tokens` field in JSON which is returned from OpenAI. Can you add this field to the `OpenAIStreamChatCompletionModel` class? Because this class is final, I can't extend it.

**Comment by anasfik** [comment]
The thing is the [chat responses chunk object](https://platform.openai.com/docs/api-reference/chat/streaming) doesn't support having the `usage` like the asynchronous [chat response object](https://platform.openai.com/docs/api-reference/chat/object)

**Comment by dominic-deantonio** [comment]
Hi @anasfik I am looking for this feature too. It seems that the chat responses chunk object _does_ include usage according to the page you linked (maybe it didn't before?), just need to include `stream_options: {"include_usage": true}`. It says it will be null until the final chunk.

![Screenshot 2024-06-07 at 3 54 57 PM](https://github.com/anasfik/openai/assets/47908648/fe63dd76-cf68-4b5f-bc77-b29ee3a12883)
