### ISSUE TITLE
[Audio] createTranscription does not have 'timestamp_granularities' parameter

### ISSUE THREAD

**Issue by mihirshahxenlabs** [anasfik/openai#156]
In `audio.createTranscription`, there is not `timestamp_granularities[]` parameter
When `responseFormat` is set to `OpenAIAudioResponseFormat.verbose_json`, the response of `segments` or `words` is also not stored in `OpenAIAudioModel` class

Reference: https://platform.openai.com/docs/api-reference/audio/createTranscription

**Comment by anasfik** [comment]
Thank you for mentioning this.
