### ISSUE TITLE
Stream api abnormality at flutter web platform

### ISSUE THREAD

**Issue by act262** [anasfik/openai#16]
I test run stream api ok if run on dart, by abnormality when flutter web , is there any different bettwen web?

**Comment by anasfik** [comment]
Hi, Thank you for reaching here!
what about other APIs, is the issue happens on all of them or just on `Stream`'s ones.

Have a good day!

**Comment by act262** [comment]
I just test `OpenAI.instance.chat.createStream`

**Comment by AlejandroArciniegas** [comment]
I have the same error here. The package works well on Android and iOS but fails on Flutter Web for the chat.createStream method.
![image](https://user-images.githubusercontent.com/28323482/226455526-c7c0d7af-c4f3-473d-abd2-ae80d057f93d.png)

**Comment by act262** [comment]
It is ok, thank @anasfik
