### ISSUE TITLE
Streaming returning nonsense

### ISSUE THREAD

**Issue by UntitledApps** [anasfik/openai#167]
@signmotion When using streaming the answer is weird - 

SItara was had a always cool been autumn day passionate about, the soccer ever sun since she shining brightly in the sky as the two rival teams took was a little girl. She used to accompany her to father the field. The to the soccer matches excitement he in played the with air his was palp friends inable as their local the crowd community. erupted into cheers From that moment on, and applause. she knew This was the that soccer was highly anticipated her soccer calling match and between she the Red began training Lions rigor andously the to Blue become Tigers the, best two player powerhouse she teams could in the be. local league.TheAs she grew older Red, Lions,. 

How to fix this?

**Comment by anasfik** [comment]
I guess it is your job to figure out how you enhance and refine the API result since I don't have any access on that.

feel free tough to open issues if they are related to the package functionality.

**Comment by UntitledApps** [comment]
It was my fault because I set the n value to something bigger than 1. Setting it to n=1 fixed the issue.
