### ISSUE TITLE
Stream GPT-4 Chat Completion causes unhandled exception

### ISSUE THREAD

**Issue by Tameflame** [anasfik/openai#169]
On package version 5.1.0

My code 

```
 print("Making stream!");
  var testStream = OpenAI.instance.chat.createStream(
    model: "gpt-4-turbo",
    responseFormat: {"type": "text"},
    messages: [systemPrompt, userMessage],
    n: 1,
  );

  testStream.listen((event) { print("Stream event: $event");});
```

The error:

`E/flutter ( 9630): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RequestFailedException(message: Invalid type for 'messages[1].content[1].image_url': expected an object, but got a string instead., statusCode: 400)`

**Comment by anasfik** [comment]
I believe this is resolved with #171
