### ISSUE TITLE
completion.createStream seems not working, it is done with no reason

### ISSUE THREAD

**Issue by mny459** [anasfik/openai#17]
api
```
OpenAI.instance.completion
          .createStream(model: model, prompt: prompt, n: 1);
```

log

```
stream response is done
```

**Comment by anasfik** [comment]
Thank you for reaching here.
can I get the full code with the `model` id and the `prompt` you used,  assuming that the `prompt` is a `String` or `List<String>`.


I runned a custom code reflecting yours:
```dart
 Stream<OpenAIStreamCompletionModel> stream =
      OpenAI.instance.completion.createStream(
    model: "text-davinci-003",
    n: 1,
    prompt: "Github is ",
  );
  stream.listen((event) {
    print(event.choices.first.text);
  });
```
and it seems to work as expected, I assume that the issue might happen from that `prompt` field since it is a `dynamic` type because this field can accept both `String` or `List<String>`.

Have a good day!

**Comment by mny459** [comment]
Think you for response. The actual code is below

```
OpenAI.instance.completion
          .createStream(model: 'text-davinci-003', prompt: '帮我写一个小马过河的教案', n: 1)
.listen((event)){
};

```

**Comment by anasfik** [comment]
Hi, I copied your code and run it and it works as expected as a `Stream`.

are you sure it is not related to another issue such as the support of your country by OpenAI?

**Comment by mny459** [comment]
> 

I am sure. Because chat works fine.

**Comment by anasfik** [comment]
I can't reproduce to check the issue actually since it does work fine when I try it:
![image](https://user-images.githubusercontent.com/25140579/226536842-2301f736-6b21-4635-a617-bb89ac760627.png)

can you try to play around with other properties such as `stop` and/or `maxTokens`?

**Comment by mny459** [comment]
I try again, maybe I misunderstand，when I use text-davinci-003, it's answer is much short than gpt-3.5-turbo, only a few words, maybe it's correct

**Comment by anasfik** [comment]
please, reach here again if you have other issues

**Comment by mny459** [comment]
Ok
