### ISSUE TITLE
Misleading documentation of OpenAI#instance

### ISSUE THREAD

**Issue by jkruke** [anasfik/openai#174]
The OpenAI.instance getter documentation says "[...] make sure to call the [OpenAI.initialize] method before accessing [instance] [...]". There is no `OpenAI.initialize` method. It has probably been removed?

https://github.com/anasfik/openai/blob/dfce769f274d0951b038488884a01772fffbf471/lib/src/instance/openai.dart#L31

**Comment by anasfik** [comment]
Thanks man for noticing this, I changed it.
