### ISSUE TITLE
Is the GTP4-o really using GPT4-o?

### ISSUE THREAD

**Issue by UntitledApps** [anasfik/openai#175]
In the dashboard it says I used GPT4 Turbo

**Comment by dreyescabrera** [comment]
I'm having the same question

**Comment by rnamilakonda** [comment]
same question.

**Comment by anasfik** [comment]
when you input `gpt-4o` in the model field of any method, it will be translated to:

```json
{
"model": "gpt-4o",
...
}
``` 

so yeah, it is using it actually.

remember that you can always log the whole HTTP requests that the package sends.
