### ISSUE TITLE
Because every version of flutter_test from sdk depends on meta 1.8.0 and bubble_up depends on meta ^1.9.0, flutter_test from sdk is forbidden. So, because bubble_up depends on flutter_test from sdk, version solving failed.

### ISSUE THREAD

**Issue by ulrich-lab** [anasfik/openai#2]

**Comment by ulrich-lab** [comment]
I try to install dart-openai but I have this error due to the meta package I am asked to migrate to version 1.9.0 but I even try with the latest version of flutter Without success

**Comment by anasfik** [comment]
the [dart_openai](https://pub.dev/packages/dart_openai) uses the latest version of [meta](https://pub.dev/packages/meta) which is 1.9.0 as of today, I don't see how you're issue relates specifically to this dart_openai.

 it seems like some other package in your flutter project uses an older version of [meta](https://pub.dev/packages/meta), which results in this conflict/error

A fix that might work for your case, is to remove the version number of the library on your `pubspec.yaml`:

From this:

```yaml
  dependencies:
     theLibrary: ^1.0.0
```

to this:
```yaml
  dependencies:
     theLibrary: 
```

just let the version number value empty like this, then run `flutter pub get`, then run your app.

**Comment by ulrich-lab** [comment]
same error how to increase meta versionBecause every version of
flutter_test from sdk depends on meta 1.8.0 and every version of
dart_openai depends on meta ^1.9.0, flutter_test from sdk is incompatible
with dart_openai.
So, because bubble_up depends on both dart_openai any and flutter_test from
sdk, version solving failed.
pub get failed

**Comment by anasfik** [comment]
I don't have any problem with downgrading the meta version so it works for you, I will set it to 1.8.0.

**Comment by anasfik** [comment]
Can you update the [dart_openai](https://pub.dev/packages/dart_openai) version to 1.0.9 :
```yaml
  dart_openai: ^1.0.9
``` 

it uses [meta ](https://pub.dev/packages/meta)at the version of 1.8.0, so it should be compatible with your project now.

**Comment by ulrich-lab** [comment]
Done. but Because every version of flutter_test from sdk depends on
collection 1.17.0 and every version of dart_openai depends on collection
^1.17.1, flutter_test from sdk is incompatible with dart_openai.
So, because bubble_up depends on both dart_openai ^1.0.9 and flutter_test
from sdk, version solving failed.
pub get failed

**Comment by anasfik** [comment]
Try now to update the version of dart_openai to 1.1.0.

**Comment by ulrich-lab** [comment]
Yes, it works.

**Comment by anasfik** [comment]
Great, if you faced any other issues, please let me know.

**Comment by ulrich-lab** [comment]
Can I have Whattsap phone number?
wa.me/+237692617975
