### ISSUE TITLE
How to handle exception？

### ISSUE THREAD

**Issue by mny459** [anasfik/openai#25]

**Comment by AlejandroArciniegas** [comment]
You might want to read the documentation, wrap the method throwing the exception with try catch.
https://github.com/anasfik/openai#error-handling

**Comment by mny459** [comment]
> You might want to read the documentation, wrap the method throwing the exception with try catch. https://github.com/anasfik/openai#error-handling

Sorry, I misstake. I did wrap my code with a try catch block, but it dit not catch anything, when I turn off my phone's network connecting, use stream method
