### ISSUE TITLE
Help needed with 'Create a chat completion stream'

### ISSUE THREAD

**Issue by Artico77** [anasfik/openai#28]
Hi! i got some doubts about how to get a stream response from **OpenAIStreamChatCompletionModel** (building a mobile app).

Looking at the doc it looks like the only thing i need to do to print the chunks of text in response is: 
```dart
chatStream.listen((chatStreamEvent) {
 print(**chatStreamEvent**); // ...
});
```

The problem is i'm getting lines like these in response:
```dart
OpenAIStreamChatCompletionModel(id: chatcmpl-6y1gmLRNdjiNwX4G2825Df94R2HQU, created: 2023-03-25 17:09:52.000, choices: [OpenAIStreamChatCompletionChoiceModel(index: 0, delta: OpenAIStreamChatCompletionChoiceMessageModel(role: null, content:  in), finishReason: null)])
OpenAIStreamChatCompletionModel(id: chatcmpl-6y1gmLRNdjiNwX4G2825Df94R2HQU, created: 2023-03-25 17:09:52.000, choices: [OpenAIStreamChatCompletionChoiceModel(index: 0, delta: OpenAIStreamChatCompletionChoiceMessageModel(role: null, content:  sol), finishReason: null)])
OpenAIStreamChatCompletionModel(id: chatcmpl-6y1gmLRNdjiNwX4G2825Df94R2HQU, created: 2023-03-25 17:09:52.000, choices: [OpenAIStreamChatCompletionChoiceModel(index: 0, delta: OpenAIStreamChatCompletionChoiceMessageModel(role: null, content: i), finishReason: null)])
```

I finally got it to work accessing '**chatStreamEvent.choices.first.delta.content**' before printing, but i don't know if this is the way it should work or i'm doing something wrong.

Thanks a lot

**Comment by anasfik** [comment]
Hello, thank you for reaching out here!

The `chatStreamEvent` is an `OpenAIStreamChatCompletionModel` class instance, which contains much information about a single message with the message itself, as you can see (its id, date of creation...) since those can be useful for some cases.

for your case, in which I assume that you need only the messages, you can specify what to return exactly in that stream by specifying its property, like this:
```dart
chatStream.listen((chatStreamEvent) {
print(chatStreamEvent.choices.first.delta.content ); // ...
})
```

**Comment by Artico77** [comment]
Hi, thanks for your quick reply. That makes sense.

I got another question for you if i may: i tried to handle an error in the stream api request and display it in a Text widget as a response, not only print it in the console.

// method to launch the api request
 static Stream<OpenAIStreamChatCompletionModel> helpRequestStream() {
    try {
      Stream<OpenAIStreamChatCompletionModel> completionStream = OpenAI.instance.chat.createStream(
        model: "gpt-3.5-turbo",
        messages: [..]
      return completionStream;
    } on RequestFailedException catch (e) {
      debugPrint("error ${e.message}");
      rethrow;
    }

// initState of my Stateful widget
@override
  void initState() {
    super.initState();
    completionStream = ApiOpenAiManager.helpRequestStream();
    completionStream.listen((chatStreamEvent) {
      setState(() {
          buffer.write(chatStreamEvent.choices.first.delta.content);
        chatText = buffer.toString();
      });
    }, onError: (error) {
      setState(() {
        chatText = 'Error: $error';
      });
    });
  }

@override
  Widget build(BuildContext context) {
    return AlertDialog(     
      content: SingleChildScrollView(
        child: chatText.isEmpty
            ? Center(child: spinkit)
            : Text(
                chatText,
                style: Theme.of(context).textTheme.bodyLarge,
              ),
      ),
    );
  }

The problem is nothing gets displayed in my Text Widget if there is an error (my loading indicator keeps going). 
Can you please help me with this?

thanks again for your work!
