### ISSUE TITLE
Flutter's macos desktop app times out

### ISSUE THREAD

**Issue by xujiangithub** [anasfik/openai#29]
In China.

[OpenAI] accessing endpoint: /models
[OpenAI] starting request to https://api.openai.com/v1/models

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Operation timed out
#0      IOClient.send
io_client.dart:88
<asynchronous suspension>
#1      BaseClient._sendUnstreamed
base_client.dart:93
<asynchronous suspension>
#2      _withClient
http.dart:164
<asynchronous suspension>
#3      OpenAINetworkingClient.get
client.dart:21
<asynchronous suspension>
#4      OpenAIModel.list

**Comment by xujiangithub** [comment]
what do i need to do

**Comment by anasfik** [comment]
hello, thank you for reaching out here!

the issue doesn't seem to be related directly to macOS.

it seems similar to #17, which throws an unexpected error for the `list()` method for models. However, I did research and found that China is not a supported country by OpenAI yet! so I guess their APIs are disabled in your region, please check the:
https://platform.openai.com/docs/supported-countries

the community noticed the issue for disabled countries by OpenAI, so the SDK `baseUrl` is exposed to be changed manually, so I guess you either need to use a VPN for another supported county or finding a proxy server that will make it work

**Comment by mny459** [comment]
> hello, thank you for reaching out here!
> 
> the issue doesn't seem to be related directly to macOS.
> 
> it seems similar to #17, which throws an unexpected error for the `list()` method for models. However, I did research and found that China is not a supported country by OpenAI yet! so I guess their APIs are disabled in your region, please check the: https://platform.openai.com/docs/supported-countries
> 
> the community noticed the issue for disabled countries by OpenAI, so the SDK `baseUrl` is exposed to be changed manually, so I guess you either need to use a VPN for another supported county or finding a proxy server that will make it work

Thanks for you code. I solved this by change `postStream` method's implementation to Dio, and support proxy config temporary。
