### ISSUE TITLE
Because every version of flutter_test from sdk depends on collection 1.17.0 and every version of dart_openai depends on collection ^1.17.1, flutter_test from sdk is incompatible with dart_openai.

### ISSUE THREAD

**Issue by yang-chao** [anasfik/openai#3]
Can you downgrade collection version to 1.17.0

Flutter: 3.7.2
environment:
  sdk: '>=2.19.1 <3.0.0'
dart_openai: ^1.1.2

**Comment by anasfik** [comment]
Hello, Thank you for reaching me.

can you try 1.2.2 version now ?

**Comment by yang-chao** [comment]
> 

Perfect, thanks!

**Comment by yang-chao** [comment]
> Hello, Thank you for reaching me.
> 
> can you try 1.2.2 version now ?

Perfect, thanks!
