### ISSUE TITLE
Overall slowness

### ISSUE THREAD

**Issue by WH-Creations** [anasfik/openai#33]
Hey there!

Just wanted to confirm some expected behavior. Calls are taking about 20 seconds to return a response, is that expected behavior?

If not, any tips on optimizing the prompt for quicker responses?

**Comment by anasfik** [comment]
Hi, yes it is what is expected from OpenAI APIs, they are relatively slow to generate one final result.

well, the solution or workaround that you can do, is to use the `Stream` based methods offered by the package, or by preloading requests for the end users
