### ISSUE TITLE
Does the web support this?

### ISSUE THREAD

**Issue by macoshita** [anasfik/openai#34]
Thank you for creating the Awesome Library.

Does the web support this?
I tried using ChatGPT and it seemed to work fine in Chrome.
If you support it, it looks like you should add web below.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/6210798/230518852-b77115cc-fe72-4ed0-a87f-5740cf62f16d.png">

**Comment by anasfik** [comment]
Hi, yes it is entended to work for the web, thank you for noticing this!
