### ISSUE TITLE
Usage in the Chat mode

### ISSUE THREAD

**Issue by rafaellop** [anasfik/openai#39]
How can I find the usage when using OpenAIStreamChatCompletionModel?

**Comment by rafaellop** [comment]
@anasfik could you please advice?

**Comment by Jegorex** [comment]
OpenAI doesn't give usage numbers when streaming. You will have to calculate it yourself if you stream.

**Comment by rafaellop** [comment]
Yes, indeed https://community.openai.com/t/usage-info-in-api-responses/18862
Closing
