### ISSUE TITLE
Stream completion is not really streamed

### ISSUE THREAD

**Issue by hlwhl** [anasfik/openai#4]
Current stream completion is not really streamed, data will returned until all data received. Consider use client.send to create a StreamedResponse.

**Comment by hlwhl** [comment]
Seems we need to make change in http. dartlang/http#869

**Comment by anasfik** [comment]
Hello [hlwhl](https://github.com/hlwhl).

Thank you for pointing this, I checked this and you have right, it is a stream but don't sink until it's it's received.

I will work on it.

**Comment by hlwhl** [comment]
Tested with following code with modified http package.
```dart
    final http.Client client = http.Client();
    var req = http.Request("POST", Uri.parse(to));
    req.body = jsonEncode(body);
    client.head(Uri.parse(to), headers: HeadersBuilder.build());
    req.headers = HeadersBuilder.build();
    OpenAILogger.log("Starting to reading stream response");
    client.send(req).then((respond) {
      respond.stream.listen((value) {
        String data = utf8.decode(value);
        print(data);
      });
    });
````

**Comment by anasfik** [comment]
Hi, [hlwhl](https://github.com/hlwhl), Thank you, I managed to use your code snippet with a combination of `StreamController` to implement it.

I did also add an example for it in example/, can you check it, please?

**Comment by hlwhl** [comment]
> Hi, [hlwhl](https://github.com/hlwhl), Thank you, I managed to use your code snippet with a combination of `StreamController` to implement it.
> 
> I did also add an example for it in example/, can you check it, please?

@anasfik Work as intended!

**Comment by rafaellop** [comment]
Hi, how to use streams with the `OpenAIChatCompletionModel`? Docs says it works with streams but I cannot find stream version of the model like for example the `OpenAIStreamCompletionModel`.
