### ISSUE TITLE
Error: FormatException: SyntaxError: Expected property name or '}' in JSON at position 1.

### ISSUE THREAD

**Issue by bsubash2054** [anasfik/openai#42]
I encountered this error when I set the maxTokens property as 4000, and upon investigation I managed to find and resolve the issue. The issue occurs in the file `packages/dart_openai/src/core/networking/client.dart` line 225 which resembles to `final error = jsonDecode(data)['error'];`. In my case setting maxTokens to 4000 fired an error: `This model's maximum context length is 4097 tokens. However, you requested 4097 tokens (97 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.`, and trying to decode this fired the error that's mentioned in the title instead.

**Comment by bsubash2054** [comment]
[OpenAI] accessing endpoint: /chat/completions
[OpenAI] starting request to https://api.openai.com/v1/chat/completions
[OpenAI] accessing endpoint: /chat/completions
[OpenAI] starting request to https://api.openai.com/v1/chat/completions
[OpenAI] Starting to reading stream response
Error: FormatException: SyntaxError: Expected property name or '}' in JSON at position 1
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/convert_patch.dart 39:5           _parseJson
dart-sdk/lib/convert/json.dart 610:36                                         convert
dart-sdk/lib/convert/json.dart 216:41                                         decode
dart-sdk/lib/convert/json.dart 155:10                                         jsonDecode
packages/dart_openai/src/core/networking/client.dart 225:29                   <fn>
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/line_splitter.dart 153:13                                [_addLines]
dart-sdk/lib/convert/line_splitter.dart 128:5                                 addSlice
dart-sdk/lib/convert/string_conversion.dart 163:5                             add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/string_conversion.dart 243:7                             addSlice
dart-sdk/lib/convert/string_conversion.dart 317:20                            addSlice
dart-sdk/lib/convert/string_conversion.dart 310:5                             add
dart-sdk/lib/convert/chunked_conversion.dart 72:18                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/async/stream_transformers.dart 211:11                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 515:13                                    perform
dart-sdk/lib/async/stream_impl.dart 620:10                                    handleNext
dart-sdk/lib/async/stream_impl.dart 591:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
Error: FormatException: SyntaxError: Unexpected non-whitespace character after JSON at position 9
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/convert_patch.dart 39:5           _parseJson
dart-sdk/lib/convert/json.dart 610:36                                         convert
dart-sdk/lib/convert/json.dart 216:41                                         decode
dart-sdk/lib/convert/json.dart 155:10                                         jsonDecode
packages/dart_openai/src/core/networking/client.dart 225:29                   <fn>
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/line_splitter.dart 153:13                                [_addLines]
dart-sdk/lib/convert/line_splitter.dart 128:5                                 addSlice
dart-sdk/lib/convert/string_conversion.dart 163:5                             add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/string_conversion.dart 243:7                             addSlice
dart-sdk/lib/convert/string_conversion.dart 317:20                            addSlice
dart-sdk/lib/convert/string_conversion.dart 310:5                             add
dart-sdk/lib/convert/chunked_conversion.dart 72:18                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/async/stream_transformers.dart 211:11                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 515:13                                    perform
dart-sdk/lib/async/stream_impl.dart 620:10                                    handleNext
dart-sdk/lib/async/stream_impl.dart 591:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
Error: FormatException: SyntaxError: Unexpected non-whitespace character after JSON at position 13
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/convert_patch.dart 39:5           _parseJson
dart-sdk/lib/convert/json.dart 610:36                                         convert
dart-sdk/lib/convert/json.dart 216:41                                         decode
dart-sdk/lib/convert/json.dart 155:10                                         jsonDecode
packages/dart_openai/src/core/networking/client.dart 225:29                   <fn>
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/line_splitter.dart 153:13                                [_addLines]
dart-sdk/lib/convert/line_splitter.dart 128:5                                 addSlice
dart-sdk/lib/convert/string_conversion.dart 163:5                             add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/string_conversion.dart 243:7                             addSlice
dart-sdk/lib/convert/string_conversion.dart 317:20                            addSlice
dart-sdk/lib/convert/string_conversion.dart 310:5                             add
dart-sdk/lib/convert/chunked_conversion.dart 72:18                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/async/stream_transformers.dart 211:11                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 515:13                                    perform
dart-sdk/lib/async/stream_impl.dart 620:10                                    handleNext
dart-sdk/lib/async/stream_impl.dart 591:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
Error: FormatException: SyntaxError: Unexpected non-whitespace character after JSON at position 10
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/convert_patch.dart 39:5           _parseJson
dart-sdk/lib/convert/json.dart 610:36                                         convert
dart-sdk/lib/convert/json.dart 216:41                                         decode
dart-sdk/lib/convert/json.dart 155:10                                         jsonDecode
packages/dart_openai/src/core/networking/client.dart 225:29                   <fn>
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/line_splitter.dart 153:13                                [_addLines]
dart-sdk/lib/convert/line_splitter.dart 128:5                                 addSlice
dart-sdk/lib/convert/string_conversion.dart 163:5                             add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/string_conversion.dart 243:7                             addSlice
dart-sdk/lib/convert/string_conversion.dart 317:20                            addSlice
dart-sdk/lib/convert/string_conversion.dart 310:5                             add
dart-sdk/lib/convert/chunked_conversion.dart 72:18                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/async/stream_transformers.dart 211:11                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 515:13                                    perform
dart-sdk/lib/async/stream_impl.dart 620:10                                    handleNext
dart-sdk/lib/async/stream_impl.dart 591:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
Error: FormatException: SyntaxError: Unexpected non-whitespace character after JSON at position 11
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/convert_patch.dart 39:5           _parseJson
dart-sdk/lib/convert/json.dart 610:36                                         convert
dart-sdk/lib/convert/json.dart 216:41                                         decode
dart-sdk/lib/convert/json.dart 155:10                                         jsonDecode
packages/dart_openai/src/core/networking/client.dart 225:29                   <fn>
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/line_splitter.dart 153:13                                [_addLines]
dart-sdk/lib/convert/line_splitter.dart 128:5                                 addSlice
dart-sdk/lib/convert/string_conversion.dart 163:5                             add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/string_conversion.dart 243:7                             addSlice
dart-sdk/lib/convert/string_conversion.dart 317:20                            addSlice
dart-sdk/lib/convert/string_conversion.dart 310:5                             add
dart-sdk/lib/convert/chunked_conversion.dart 72:18                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/async/stream_transformers.dart 211:11                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 515:13                                    perform
dart-sdk/lib/async/stream_impl.dart 620:10                                    handleNext
dart-sdk/lib/async/stream_impl.dart 591:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
Error: FormatException: SyntaxError: Unexpected non-whitespace character after JSON at position 10
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/convert_patch.dart 39:5           _parseJson
dart-sdk/lib/convert/json.dart 610:36                                         convert
dart-sdk/lib/convert/json.dart 216:41                                         decode
dart-sdk/lib/convert/json.dart 155:10                                         jsonDecode
packages/dart_openai/src/core/networking/client.dart 225:29                   <fn>
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/line_splitter.dart 153:13                                [_addLines]
dart-sdk/lib/convert/line_splitter.dart 128:5                                 addSlice
dart-sdk/lib/convert/string_conversion.dart 163:5                             add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/string_conversion.dart 243:7                             addSlice
dart-sdk/lib/convert/string_conversion.dart 317:20                            addSlice
dart-sdk/lib/convert/string_conversion.dart 310:5                             add
dart-sdk/lib/convert/chunked_conversion.dart 72:18                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/async/stream_transformers.dart 211:11                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 515:13                                    perform
dart-sdk/lib/async/stream_impl.dart 620:10                                    handleNext
dart-sdk/lib/async/stream_impl.dart 591:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
Error: FormatException: SyntaxError: Unexpected token '}', "  }" is not valid JSON
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/convert_patch.dart 39:5           _parseJson
dart-sdk/lib/convert/json.dart 610:36                                         convert
dart-sdk/lib/convert/json.dart 216:41                                         decode
dart-sdk/lib/convert/json.dart 155:10                                         jsonDecode
packages/dart_openai/src/core/networking/client.dart 225:29                   <fn>
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/line_splitter.dart 153:13                                [_addLines]
dart-sdk/lib/convert/line_splitter.dart 128:5                                 addSlice
dart-sdk/lib/convert/string_conversion.dart 163:5                             add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/string_conversion.dart 243:7                             addSlice
dart-sdk/lib/convert/string_conversion.dart 317:20                            addSlice
dart-sdk/lib/convert/string_conversion.dart 310:5                             add
dart-sdk/lib/convert/chunked_conversion.dart 72:18                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/async/stream_transformers.dart 211:11                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 515:13                                    perform
dart-sdk/lib/async/stream_impl.dart 620:10                                    handleNext
dart-sdk/lib/async/stream_impl.dart 591:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
Error: FormatException: SyntaxError: Unexpected token '}', "}" is not valid JSON
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/convert_patch.dart 39:5           _parseJson
dart-sdk/lib/convert/json.dart 610:36                                         convert
dart-sdk/lib/convert/json.dart 216:41                                         decode
dart-sdk/lib/convert/json.dart 155:10                                         jsonDecode
packages/dart_openai/src/core/networking/client.dart 225:29                   <fn>
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/line_splitter.dart 153:13                                [_addLines]
dart-sdk/lib/convert/line_splitter.dart 128:5                                 addSlice
dart-sdk/lib/convert/string_conversion.dart 163:5                             add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/convert/string_conversion.dart 238:11                            add
dart-sdk/lib/convert/string_conversion.dart 243:7                             addSlice
dart-sdk/lib/convert/string_conversion.dart 317:20                            addSlice
dart-sdk/lib/convert/string_conversion.dart 310:5                             add
dart-sdk/lib/convert/chunked_conversion.dart 72:18                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 271:7                                     [_add]
dart-sdk/lib/async/stream_transformers.dart 63:11                             [_add]
dart-sdk/lib/async/stream_transformers.dart 13:11                             add
dart-sdk/lib/async/stream_transformers.dart 211:11                            add
dart-sdk/lib/async/stream_transformers.dart 111:24                            [_handleData]
dart-sdk/lib/async/zone.dart 1593:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 515:13                                    perform
dart-sdk/lib/async/stream_impl.dart 620:10                                    handleNext
dart-sdk/lib/async/stream_impl.dart 591:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

**Comment by zhoujian-official** [comment]
same problem here

**Comment by anasfik** [comment]
Hello, thank you for reaching out here!

I will reproduce and fix the issue ASAP.

Thank you!
