### ISSUE TITLE
Support for Azure OpenAI

### ISSUE THREAD

**Issue by lijy91** [anasfik/openai#43]
I hope to increase support for [Azure OpenAI](https://azure.microsoft.com/en-us/products/cognitive-services/openai-service), just like the `openai-python` Python library.

```python
#Note: The openai-python library support for Azure OpenAI is in preview.
import os
import openai
openai.api_type = "azure"
openai.api_base = "https://example.openai.azure.com/"
openai.api_version = "2022-12-01"
openai.api_key = os.getenv("OPENAI_API_KEY")

response = openai.Completion.create(
  engine="gpt-35-turbo",
  prompt="",
  temperature=1,
  max_tokens=100,
  top_p=0.5,
  frequency_penalty=0,
  presence_penalty=0,
  stop=None)
```

**Comment by huozhong-in** [comment]
This feature is strongly needed! Please bro!

**Comment by anasfik** [comment]
Hello, thank you for reaching out here!

Sure, we can include it in `dart_openai` as well, I will work on it ASAP!

thank you!

**Comment by yaoshenwang** [comment]
Thank you! We really need the support of Azure Openai

> Hello, thank you for reaching out here!
> 
> Sure, we can include it in `dart_openai` as well, I will work on it ASAP!
> 
> thank you!

**Comment by abasu0713** [comment]
Upvoting this please! 👍

**Comment by anasfik** [comment]
The work on the Azure implementation is done in the `azure` branch, please provide me with feedback and manual tests/use of it because I will reflect it from the Python library.

**Comment by anasfik** [comment]
some work is already being implemented, this needs to be really tested since I edited the core module in the package, please can I get any feedback on it?

**Comment by anasfik** [comment]
Hello @lijy91 @abasu0713 @gavinliu @yaoshenwang @gavinliu.

Does any of you have a valid account on Azure OpenAI, I need someone to make tests with valid his valid deployment so I can review, Fix, and merge it.

Thank you!

**Comment by anasfik** [comment]
The progress on Azure is stopping..

I will close this for now!

**Comment by abasu0713** [comment]
@anasfik sorry about missing this thread.. Unfortunately I don't.. Let me get that going and I will hit you back later during the week.
