### ISSUE TITLE
UnHandled exception _ClientSocketException 

### ISSUE THREAD

**Issue by ALIxAHMAD** [anasfik/openai#44]
When I try to get chat completion stream and there is no internet connection this error happens, and I cant use a 'try-catch' since the package returns the stream before the connection is done.
my code :
 ``` dart
Future<Stream<ItemBodyCompletion>> itemBodyCompletionStream(
    String system,
    String user,
    String assistant,
  ) async {
    final bodyCompletion = openAI.chat.createStream(
      model: "gpt-3.5-turbo",
      messages: [
        OpenAIChatCompletionChoiceMessageModel(
          role: OpenAIChatMessageRole.system,
          content: system,
        ),
        OpenAIChatCompletionChoiceMessageModel(
          role: OpenAIChatMessageRole.user,
          content: user,
        ),
        OpenAIChatCompletionChoiceMessageModel(
          role: OpenAIChatMessageRole.assistant,
          content: assistant,
        ),
      ],
    );
    final stream = StreamController<ItemBodyCompletion>();
    bodyCompletion.listen((event) {
      return stream
          .add(ItemBodyCompletion(body: event.choices[0].delta.content ?? ""));
    }, onDone: () {
      stream.close();
    }, onError: (e) {
      stream.addError(e);
    });
    return stream.stream;
  }
```
I am already using a try-catch statement when calling this function but the error is not caught or passed to stream's onError.
Exception is happening in io_client.dart file line 88 like this :
_ClientSocketException (Failed host lookup: 'api.openai.com')

**Comment by anasfik** [comment]
Hello, thank you for reaching out here!

I reproduced and yes, this must be caught meanwhile it doesn't.

I will fix it right now and publish the 1.9.8 version.

Thank you

**Comment by anasfik** [comment]
hello, I did fix the issue and now all errors should be caught with the onError method of the stream, please upgrade to version 1.9.8.

I did also included your example in the examples/ where I confirmed it.

Thank you!

**Comment by jonny7737** [comment]
Using 1.9.8:

[OpenAI] starting request to https://api.openai.com/v1/chat/completions
[OpenAI] Starting to reading stream response
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RequestFailedException{message: That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 1612fd911aef30e1ccdc968d3c377ff8 in your message.), statusCode: 429}

Any way to catch this?  I'd like to display a dialog to inform the user.

**Comment by anasfik** [comment]
Hi @jonny7737.

Are you requesting this with the `create()` or `createStream()` method?

**Comment by jonny7737** [comment]
Sorry for not being clear.  'Starting to reading stream response', indicates that this is from the createStream(). 

BTW:  Awesome package.  Thank you for your efforts.

**Comment by ALIxAHMAD** [comment]
Hi @anasfik 
I upgraded to 1.9.8 and it is working fine.
Thank you for your great efforts on this amazing library.
