### ISSUE TITLE
How to cancel a stream?

### ISSUE THREAD

**Issue by richardchui** [anasfik/openai#45]
When using chat completion with streaming, how can we stop the server from further streaming?  And will the onDone code be executed?  Thanks!

**Comment by anasfik** [comment]
Hi, thank you for reaching out here!

I'm not sure what you mean by canceling a stream, if you mean that you want to stop the whole process of generating token responses at a particular time from the OpenAI end, then it is impossible and you will be required to make a get billed for the whole generated response.

if you mean that you just want to stop the stream inside your app even though you will get billed for all generated tokens, then you can use a `StreamSubscription` to subscribe and control the listened stream, first import `dart:async` in your code then you can do something like this:

```dart
 // We create the stream here.
 Stream stream = OpenAI.instance.completion.createStream(/.../);

 // We associate the listen() to a StreamSubscription.
 StreamSubscription sub = stream.listen((res) => print(res.choices));

 // We wait for a certain duration for example.
 await Future.delayed(Duration(seconds: 1));

 // Then we cancel the subscription to stop.
 sub.cancel();
```

This is just an example that you can check to see, however, this will stop it only in your Dart/Flutter app, but you will get billed for all the response tokens by OpenAI.

**Comment by richardchui** [comment]
@anasfik Thank you for the detail response.  I didn't realize you cannot stop the token generation process.  But being able to  cancel the subscription is probably good enough.  I saw on the OpenAI site that you can stop the response, so I am just wondering how it can be done. 

Thanks again for the great help!
