### ISSUE TITLE
how to make AI remember my conversation?

### ISSUE THREAD

**Issue by abehbatre** [anasfik/openai#46]
<img width="224" alt="image" src="https://user-images.githubusercontent.com/36602270/236694389-5d137ccc-c7ca-46be-b342-bd8431b58e44.png">

this my code:

```dart
Future<void> onSend() async {
  /// prevent force click
  if (isGenerating.value || tfMessage.text.isBlank!) {
    return;
  }

  /// insert => ME
  listResponse.insert(0, ChatMessage(data: Data(who: CHAT_ME, message: tfMessage.text)));

  /// clean
  // tfMessage.text = '';
  isGenerating.value = true;

  /// insert => BOT
  await OpenAI.instance.chat.create(
    model: 'gpt-3.5-turbo',
    messages: [
      OpenAIChatCompletionChoiceMessageModel(
        content: tfMessage.text,
        role: OpenAIChatMessageRole.user,
      ),
    ],
  ).then((response) {
    response.choices.forEach((element) {
      isGenerating.value = false;
      listResponse.insert(0, ChatMessage(data: Data(who: CHAT_BOT, message: element.message.content)));
      scrollController.animateTo(0.0, curve: Curves.easeOut, duration: const Duration(milliseconds: 300));
    });
  }).catchError((e) {
    isGenerating.value = false;
    listResponse.insert(0, ChatMessage(data: Data(who: CHAT_BOT, message: '$e')));
  });
}
```

**Comment by khalifa007** [comment]
OpenAIChatCompletionChoiceMessageModel(
        content: tfMessage.text,
        role: OpenAIChatMessageRole.user,
      ),


add more OpenAIChatCompletionChoiceMessageModel() this in messages list when request

**Comment by anasfik** [comment]
Hello thank you for reaching here, I would love to take you and explain it to you based on your example, but first, please provide me with a full minimal code sample including the model classes you're using, and you're hidden variables such as CHAT_ME...

and if you can build host a minimal flutter app that I can run, it would be better so I can work on it and explain to you.
