### ISSUE TITLE
Allow user to provide their own HTTP client.

### ISSUE THREAD

**Issue by MichealReed** [anasfik/openai#47]
Per this issue -- https://github.com/invertase/dart_edge/issues/34 this library is hard to use with serverless functions. It would be nice if this library allowed users to provide their own HTTP client for use such as supabase or https://pub.dev/documentation/googleapis_auth/latest/auth_io/clientViaServiceAccount.html.

**Comment by anasfik** [comment]
Hello, thank you for mentioning this!

Please, if you can, can you provide me with a clear explanation of the difference between having an internal http client and providing a way to assign a new one externally.

and if I am getting it right, you mean that all methods in client.dart should use that http client, right?

Thank you

**Comment by MichealReed** [comment]
Exactly. Sometimes environments have specific requirements that cause devs to modify or create their own HTTP client. If we could optionally specify our own client and all methods used the custom http, devs could fix these problems without submitting issues here.

**Comment by anasfik** [comment]
Seems good to me, working on it!

**Comment by anasfik** [comment]
starting from 1.9.93, all package method that uses an HTTP client internally offers now the option to set your custom client to:
```dart
final cmpl = await OpenAI.instance.completion.create(
  // ...
  client: MyCustomClient(),
);
```

**Comment by MichealReed** [comment]
@anasfik is there a way to update the instance's client globally? This works for completions but I cannot use with other modules like transcription.
