### ISSUE TITLE
Allow Custom Headers for custom backEnd or FireBase AppCheck

### ISSUE THREAD

**Issue by khaledmoalla** [anasfik/openai#51]
Please allow Custom Headers especially for firebase Appcheck
so the requests can be authenticated by the backend when using a custom base url pointing to an custom endpoint protected by Appcheck

**Comment by anasfik** [comment]
Seems good to have, I will provide external method for adding custom headers.

**Comment by anasfik** [comment]
The package allows now to add custom headers to ll requests via:

```dart
OpenAI.includeHeaders({"key": "value"});
```

you will need to upgrade to the latest version of the package

**Comment by khaledmoalla** [comment]
could you add support for dart 2.18 sdk ?

**Comment by anasfik** [comment]
I already used Dart 3 new features such as class modifiers, so the package doesn't just support version lower than 3.0.0, otherwise, it will throw errors.

**Comment by Shajeel-Afzal** [comment]
@khaledmoalla can you please guide how can we use custom endpoint with this library.
