### ISSUE TITLE
Cannot mock for final class

### ISSUE THREAD

**Issue by gdutpxz** [anasfik/openai#52]
I'm testing a project using dart_openai. I need to mock all openai requests.  
I got error: 
``` The class 'OpenAIImageModel' can't be implemented outside of its library because it's a final class. ``` 

The offical issue said they will not support final class  mock: 
[Mocking final classes? ](https://github.com/dart-lang/mockito/issues/635)

Will you remove the `final` modifier ? or any workaround?

**Comment by anasfik** [comment]
Hi, 

the `OpenAIImageModel` is just a model class that holds the responses coming from the package's image methods, I don't see why you would mock it since it is just a holder for the creation date and data if that image.

if you're looking to test all the package methods to ensure that they work just fine, please fork the repository and run `openai_test.dart` file with your own API key.

**Comment by gdutpxz** [comment]
> 

Hi. Thanks for your work and response~

My project is using openai, so I need to mock its response, to verify my program's behavior.

the mock of `OpenAIImageModel` is done by the lib `Mockito` 

My code looks like
```dart

@GenerateMocks([ChatGPT])
import 'chat_gpt.mocks.dart';

class ChagGPT {
  Future<OpenAIImageModel> genImage(String imageDesc) async {
  }
}
```

and mock annotation will generate code like this:

```dart
class _FakeOpenAIImageModel_1 extends _i1.SmartFake
    implements _i2.OpenAIImageModel {
  _FakeOpenAIImageModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

@override
 @override
  _i4.Future<_i2.OpenAIImageModel> genImage(String? imageDesc){
  //...
}
```

!!And now I know I can make my ChatGPT be an interface and take an `FAKE object` to solve this problem instead of mock it.
but it's still a problem for people who like to mock it.

Again, Thanks for your work

**Comment by anasfik** [comment]
Thank you, this will be considered in the next releases by removing new class modifiers on the package models
