### ISSUE TITLE
why does it need dart sdk >=3.0

### ISSUE THREAD

**Issue by hpsoar** [anasfik/openai#56]
This will force upgrade of current dev environment.
Is it mandatory?

**Comment by gdutpxz** [comment]
relate to : https://github.com/anasfik/openai/issues/52 
in Dart 3.0: 

```
The following declarations can no longer be implemented or extended:

MapEntry
OutOfMemoryError
StackOverflowError
Expando
WeakReference
Finalizer
```

that make mockito not working

**Comment by anasfik** [comment]
no, it is not mandatory, this will be considered to be fixed by removing the new class modifiers!
