### ISSUE TITLE
ChatGPT API is released

### ISSUE THREAD

**Issue by tapkain** [anasfik/openai#6]
https://platform.openai.com/docs/api-reference/chat

**Comment by anasfik** [comment]
Hello, thank you for letting me know about this, I will be working on it ASAP!

and I'm open and willing to review/accept a pull request in case you want to contribute.

**Comment by anasfik** [comment]
Hello @tapkain, I did add the new chatGPT API method for creation as you requested, I added an example for it in example/lib/ and tests for it.

feel free to use it and provide feedback about anything, I'm planning to add another method for leveraging the creation with `Stream`

**Comment by rafaellop** [comment]
How to use streams with the OpenAIChatCompletionModel? Docs says it works with streams but I cannot find any stream version of the model like for example the OpenAIStreamCompletionModel.

**Comment by anasfik** [comment]
hello @rafaellop, sorry for this, I'm working in fixes and implementations to use it.

**Comment by anasfik** [comment]
hello @rafaellop 
the stream functionality is implemented and tested in version 1.6.1 which is currently uploading, please use it and feel free to open any other issues threads if you faced any.

thank you and have a good day.

**Comment by rafaellop** [comment]
Thank you very much @anasfik 
I'll check it out.
