### ISSUE TITLE
How to stream any url?

### ISSUE THREAD

**Issue by meulencv** [anasfik/openai#60]
Hello,
could you explain to me how to stream any url?
Please?
Even if it's not with this library, and it's natively in flutter.

For example, stream this
https://api.betterapi.net/youchat?inputs=hola&stream=True&key=site

Thanks!

**Comment by anasfik** [comment]
Hi, if I am getting this right, you want to stream responses of a specific API that supports Server-Sent Events (SSE), and it is not related to the library, right?

if yes then I will love to help you with this and write a short tutorial about it, however, this is still not the right place for it, so it would be better if you reach me by mail at [work@gwhyyy.com](mailto:work@gwhyyy.com) or by asking on Stackverflow then tagging me on it ([my profile](https://stackoverflow.com/users/18670641/gwhyyy)).

I will close this curerntly.

**Comment by meulencv** [comment]
Yes,
Thanks 
I will contact you :)

**Comment by meulencv** [comment]
Question done :)
https://stackoverflow.com/questions/76502116/how-to-stream-responses-of-a-specific-api-that-supports-server-sent-events-sse

thanks
