### ISSUE TITLE
Error Whisper formatting to srt, vtt

### ISSUE THREAD

**Issue by triay0** [anasfik/openai#63]
Hi I'm trying to transcribe a file to srt or vtt.

thats my code:

>    var transcription = await OpenAI.instance.audio.createTranscription(
>       file: File(file),
>       model: "whisper-1",
>       language: "en",
>       responseFormat: OpenAIAudioResponseFormat.srt
>     );
>       var transcriptionResult = transcription.text;

But it throws this error:

> VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected character (at line 2, character 1)
> 00:00:00,000 --> 00:00:06,320
> ^
> 
> #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
> #1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:913:48)
> #2      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
> #3      JsonDecoder.convert (dart:convert/json.dart:610:36)
> #4      JsonCodec.decode (dart:convert/json.dart:216:41)
> #5      jsonDecode (dart:convert/json.dart:155:10)
> #6      OpenAINetworkingClient.decodeToMap (package:dart_openai/src/core/networking/client.dart:535:12)
> #7      OpenAINetworkingClient.fileUpload (package:dart_openai/src/core/networking/client.dart:475:46)
> <asynchronous suspension>
> #8      OpenAIAudio.createTranscription (package:dart_openai/src/instance/audio/audio.dart:56:12)
> <asynchronous suspension>
> #9      OpenAiDataSourceImpl.transcribeFile (package:voicetotext/data/network/datasource/impl/openai_datasourc<…>

**Comment by anasfik** [comment]
Thank you for noticing this and reaching here, this is solved and will be available on the new release.
