### ISSUE TITLE
Upgrade http to ^1.0.0

### ISSUE THREAD

**Issue by koodimetsa** [anasfik/openai#67]
Currently package uses http ^0.13.5 which prevents package usage in projects with http ^1.0.0.

fetch_client has now been updated to use ^1.0.1 so upgrade is possible.

**Comment by anasfik** [comment]
Thank you for noticing this, then we can use it as well in `dart_openai`

**Comment by anasfik** [comment]
The `http` package version is now updated to `1.1.0` and will be available for use in the next pub release!

**Comment by davidmigloz** [comment]
do you have an ETA for when this will be released? 🙂
