### ISSUE TITLE
Add functions

### ISSUE THREAD

**Issue by mirkancal** [anasfik/openai#68]
https://platform.openai.com/docs/guides/gpt/function-calling

**Comment by TomerAmran** [comment]
please!

**Comment by alpha-se** [comment]
Added PR: https://github.com/anasfik/openai/pull/70

**Comment by anasfik** [comment]
Thanks to @alpha-se and @davidmigloz, the functions feature is added currently to dart_openai. just a few more tests and it will be shipped to the pub for use.

**Comment by davidmigloz** [comment]
any ETA when you expect to release it on pub.dev? 🙂

**Comment by anasfik** [comment]
Version 3.0.0 of the package is live now on Pub.

**Comment by davidmigloz** [comment]
thank you very much!! 🚀🚀
