### ISSUE TITLE
Creating completionStream with functions

### ISSUE THREAD

**Issue by Katekko** [anasfik/openai#76]
Why its not possible to create completionStream with functions today?

**Comment by Amonc** [comment]
It says it has the functionality to call the functions in the streams, but no arguments can be passed.

**Comment by Katekko** [comment]
So do we need to wait anyone to code the right way to pass the arguments?

**Comment by Tryad0** [comment]
Update is appreciated.

**Comment by MarcelHofi** [comment]
Looking forward to updates on this as well.

**Comment by anasfik** [comment]
This is implemented in the `main` branch, it will be tested and released in the next version!
