### ISSUE TITLE
Hello, how to using this lib on my self-hosted openai API like LLM?

### ISSUE THREAD

**Issue by luohao123** [anasfik/openai#78]
Hello, how to using this lib on my self-hosted openai API like LLM?

**Comment by Amonc** [comment]
@luohao123  What do you mean by self-hosted LLM? Could you explain a bit more?

**Comment by scris** [comment]
If you're just meaning self-hosted openai API, you do this by: 
```
OpenAI.baseUrl = "http(s)://your-api-server-url";
```

**Comment by anasfik** [comment]
As @scris said, if you need to change the base API url to your self-hosted one, then you can set it directly.

otherwise, can you put me on more context and clarify more what is the issue exactly.
