### ISSUE TITLE
Support https? 

### ISSUE THREAD

**Issue by lucasjinreal** [anasfik/openai#83]
Am using self-hosted llms and can not get a response, while the other frontend works normally.

Also, please consider making `openAI.baseUrl` can be printable.

**Comment by anasfik** [comment]
Can you put me in more context with your self-hosted llms so I can know exactly what is the issue?

And yes, the `OpenAI.baseUrl` do have now a getter that is exposed so you can use it in your apps, the changes are made and will be available in the next release for use.
