### ISSUE TITLE
'OpenAIEmbeddingsModel' class not found after upgrade to version 3.0.0

### ISSUE THREAD

**Issue by wednesdei** [anasfik/openai#87]
**Describe the bug**
After upgrading to version 3.0.0 from 2.0.1, the `OpenAIEmbeddingsModel` class is no longer recognized by the Dart compiler, resulting in an `Undefined class` error.

The official example doesn't work with `3.0.0`, but works with `2.0.1`:

```dart
OpenAIEmbeddingsModel embeddings = await OpenAI.instance.embedding.create(
 model: "text-embedding-ada-002",
 input: "This is a text input just to test",
);
```

**To Reproduce**

- Declare a variable of type `OpenAIEmbeddingsModel` as such: 

```dart
OpenAIEmbeddingsModel? model;
```

- The Dart analysis server will highlight `OpenAIEmbeddingsModel` and the hover tooltip will show the error: 

> Undefined class OpenAIEmbeddingsModel.

**Expected behavior**
The `OpenAIEmbeddingsModel` class should be recognized as it was in version `2.0.1`.

**Comment by anasfik** [comment]
Thank you for the great & clear issue you are having here, it is helpful.

I'am reproducing and fixing the issue right now.

**Comment by anasfik** [comment]
Hi, as I do try to reproduce your case, by delcaring a simple `main` function:
```dart 
import 'package:dart_openai/dart_openai.dart';

void main() {
 OpenAIEmbeddingsModel? model;
}
```

I see no issue at all and the `OpenAIEmbeddingsModel` get read properly as itthe package contains it.

What I suspect here is that you forgot to import the package dependency in your file, please re-check and reach me.
