### ISSUE TITLE
Fetch chat stream on web with Custom Endpoints

### ISSUE THREAD

**Issue by Zia-Bashir** [anasfik/openai#89]
I'm fetching stream chat from openAI using: 

```dart
OpenAI.apiKey = Env.apiKey;
```

What if we want to get a chat stream from the custom endpoint of OpenAI? We have placed the key in the backend and made a custom endpoint and want to fetch stream on the web. Is it possible to use this library?

**Comment by anasfik** [comment]
Hello, this package is made to support OpenAI REST APIs, it will not support allowing to change endpoints of each endpoint, but here are some solutions you can do:
 
- Fork the repository and make these changes in the endpoint of each module manually to meet your expectations.
- make your endpoints similar to OpenAI's and then replace only the `baseUrl` with your deployed server REST API:
```dart
OpenAI.baseUrl = "YOUR_SERVER_URL"
```
if there are no changes in the fields and responses by your server, the package should work fine as it is currently.
