### ISSUE TITLE
Context chat conversation Error

### ISSUE THREAD

**Issue by leenorshn** [anasfik/openai#9]
How to manage conversation context using you api?
My chatbot does not have possibility for remember chat convesation even if we are on the same page
How can I fix this hug essue

**Comment by anasfik** [comment]
hello, this was not possible before using only the completions API provided by OpenAI, however, the chat completions API is now available for developers, and it is now also available in `dart_openai`.

please make sure you have a version 1.6.0+ installed of `dart_openai`, then check this [part of the documentation](https://github.com/anasfik/openai#chat-chatgpt) which
