### ISSUE TITLE
Remember the last conversation

### ISSUE THREAD

**Issue by amjad07** [anasfik/openai#90]
can you please update us how we can custom open ai plugin so it remember the last conversations. 

for example if we say "my favourite color is blue" and then ask "what is my favourite color" it should say "blue is your favourite color"

many thanks

**Comment by jonny7737** [comment]
OpenAI APIs are stateless - they do not remember anything you do not provide in the current call. The developer must keep track of the conversation messages (user and AI) and pass those message in each chat API call or at least the messages deemed to be relevant.

Hope this helps.

**Comment by davidmigloz** [comment]
https://github.com/davidmigloz/langchain_dart may help you with that

**Comment by anasfik** [comment]
Hello @amjad07.

This is not going to be implemented or rather the goal of this package, as a developer implementing such a behavior is your task to do in your app.

Thanks @jonny7737 for clarifying this.
