### ISSUE TITLE
Stream Response is broken

### ISSUE THREAD

**Issue by praganoid** [anasfik/openai#93]
Model: gpt-3.5-turbo
System Prompt: You are a helpful assistant

Response #1
Input: What is the largest mammal in the world
Response: The mammal the the whale It of to98 feet (30) and over 200 tons

Response #2
Input: What is the tallest building in the world
Response: the, but foundation for only can build your tall as Bur Khalifa

What suppose to be the problem here? I correctly setup the flutter and dart_openai. Whenever I give an input, the response is always broken English.

**Comment by idkman666** [comment]
I have encountered the same issue.
Model: text-davinci-003

I tried both Stream<OpenAIStreamCompletionModel>  and Stream<OpenAIStreamChatCompletionModel>, but response seems to be skipping words.

**Comment by praganoid** [comment]
I think there's a problem when parsing the data on the streaming models.fromJson methods

**Comment by jaded0** [comment]
I can confirm that this still is a problem.

**Comment by anasfik** [comment]
This is fixed and will be available in the next version.
