### ISSUE TITLE
Support for GPT-4

### ISSUE THREAD

**Issue by sparkmobi** [anasfik/openai#97]
Hello,

please add the support of GPT-4, in GPT-4 you can send an image through api and openai will response with the answer

**Comment by lucasjinreal** [comment]
@anasfik  Please add support

**Comment by anasfik** [comment]
Hello @sparkmobi.

This is scheduled after resolving older issues.

**Comment by anasfik** [comment]
Hello,

This is implemented and will be ready for use in the next release, we will have a breaking change which is that the `content` of the `messages` will allow for a list of items such as `text` which is what was allowed before, but this adds now ability to create image url type.

This is closed as completed.

**Comment by becjit** [comment]
@anasfik Thanks for the package. Any tentative ETA for the next release?

**Comment by lucasjinreal** [comment]
Does it released? For image url support?
